### PR TITLE
Added swipe to dismiss gesture

### PR DESCRIPTION
**Pull request by josejuanqm**
Currently only working as a "pull to dismiss feature"

Edited:
- PresentrController.swift
— Lines 22-30, 62-65, 74, 85, 109-111, 158-202
- Presentr.swift
— Lines 62-64, 170

### CODE REVIEW

**Comment by danlozano** [comment]
Sorry!

Let me check it out and if it's all good I'll merge it 👍

**Comment by danlozano** [comment]
Was busy with al the Swift 3 crazyness 😂

**Comment by josejuanqm** [comment]
@danlozano haha no problem, thanks! 👍

**Comment by patthehuman** [comment]
@danlozano cool! 🎉

**Comment by patthehuman** [comment]
😖

**Comment by danlozano** [comment]
@patthehuman THIS ENDS TONIGHT!

I'm merging the new swift3 stuff on master back on to develop that was still swift 2.2. After that, I shall merge you're work :)

**Comment by danlozano** [comment]
DONE!

Had to convert the develop branch to swift3 since it had some new stuff on it that was not on master yet.

Then had to merge your stuff onto develop and refactor that for swift3 as well.

Think everything is working now! Should have a new release on master soon.

thanks for your patience, and good work, the new feature looks nice! 👍

**Comment by josejuanqm** [comment]
Hey! just wanted to say thanks, and i hope i could contribute a little more on the future.

Great lib! 👍

**Comment by danlozano** [comment]
Thanks!

Your feature looks pretty nice! Maybe in the future we can see what more dismissal types/gestures we can think of.

👍

**Pull request merged**
