### PR TITLE
added dismissOnTap option

### PR DESCRIPTION
**Pull request by benaneesh**
Lets users have an option of disabling the tap to dismiss action.

### CODE REVIEW

**Comment by danlozano** [comment]
Looks pretty good!

I know it's my fault for not putting the contribution guidelines, but I think the best way to keep this organized is if we create the pull requests from the forked develop branch to this develop branch. Instead of going from Master to Master, as that branch is mainly for releases.

But I'll ignore that this time. This looks pretty good, thanks for the contribution!

**Comment by danlozano** [comment]
I'll test this and add it to the next release as soon as I can :)

**Comment by benaneesh** [comment]
Thanks, and yes, my bad actually. Did this pretty fast and didn't think about it. Nice framework btw, awesome work!

Also let me know if I can help in any way.

**Comment by danlozano** [comment]
Thank you for contributing!  ... The new version 0.1.7 includes these changes (AND your other pull request as well 👍 ). Checkout the readme for the instructions as well.

Yeah will do. I'm planning on adding some Issues with the "help needed" tag. If you want to help some more :)

**Pull request merged**
