### PR TITLE
Enable keyboard translation for non popup

### PR DESCRIPTION
**Pull request by oxozle**
For developers who want to enabled keyboardTranslationType we should give it option. To use on risk.

### CODE REVIEW

**Comment by danlozano** [comment]
Yeah, I've been wanting to make this work but I'm afraid of it having weird results.

But maybe we should just go ahead and fix it your way.

I've been really busy lately, but I'll give it some thought over the weekend and fix it.

Thanks :)

**Comment by gabrielPeart** [comment]
@oxozle Didn't have time to try it out. Is there any side effects? Performance degradation? Did you try it out exhaustively?

**Comment by oxozle** [comment]
@gabrielPeart I have no problem, when turned this function on. Also all developers should make their own view controllers to make this feature available. I think this is ok as solution, because developer can disable it.

**Comment by virusman** [comment]
Please merge this feature.

**Pull request merged**
