### PR TITLE
Enhancement - Top and bottom position added with custom margin

### PR DESCRIPTION
**Pull request by Abdul-Moiz**
Added top center and bottom center position with custom margin with
support to iPad split view and slide over view. As custom origin/point
is not supporting it.

### CODE REVIEW

**Comment by Abdul-Moiz** [comment]
presentr-enhancement

**Comment by danlozano** [comment]
This looks pretty good, thanks!

Will look over it on the weekend, merge it if it's complete, and add it to the next release prob. coming out over the weekend.

:)

**Comment by gabrielPeart** [comment]
Yes, it looks really cool! Thank you @Abdul-Moiz I would just encourage you to do not commit your changed to the Xcode project (regarding team and similar stuff), there is no need to do so and will just give us the extra trouble to change.

**Comment by Abdul-Moiz** [comment]
@gabrielPeart Will remember not to push project level changes.

**Comment by danlozano** [comment]
Hi!

Couldn't you achieve this using `ModalSize` ?

You use the `ModalCenterPosition` to position your view controller, and then you use the `ModalSize` property to add the margins?

If I'm missing something please create new PR explaining the issue and without the xcodeproj.

Thanks for your patience!

**Comment by Abdul-Moiz** [comment]
Hi @danlozano,

The problem I faced with **ModelSize** and **ModalCenterPosition** is that it don't re-adjust itself with iPad multitasking. Every time I tried to change multitasking window size it keeps presentr on same position even if it's clipping or hidden behind view. + I wasn't able to find anything to change these properties at runtime.

**Pull request closed without merging**
