### PR TITLE
First Swift3 commit

### PR DESCRIPTION
**Pull request by lfarah**
Updated code to new Swift 3, including lowercase enums and new "Swifty" methods. Ex:

This:
``` swift
dismissViewControllerAnimated(dismissAnimated, completion: nil)		
```
becomes:
``` swift
self.dismiss(animated: dismissAnimated, completion: nil)
```

### CODE REVIEW

**Comment by gabrielPeart** [comment]
@lfarah thanks for contributing!
I'm going to review your code. Could you add a description for your pull request? A briefly description about what you have done. :)

**Comment by danlozano** [comment]
This strategy seems smart:

http://www.jessesquires.com/migrating-to-swift-3/

**Comment by lfarah** [comment]
@danlozano this post was from July 25. Now we can push it to master since Xcode 8 was launched and developers need this lib working

**Comment by gabrielPeart** [comment]
@lfarah  @danlozano  we have created a new branch with a complete migration fully operational with the last Xcode release, we are going to test and refactor the code and merge into master.

**Comment by lfarah** [comment]
@gabrielPeart Awesome! 🎉

**Comment by danlozano** [comment]
Yes, should be live today at night after I get off work. Thanks for your patience!

**Pull request closed without merging**
